name: Run Main File

on:
  schedule:
    - cron: "*/30 * * * *" # At 18:00 on woking days "0 18 * * 1-5" or every 30 min cron: "*/30 * * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}  # Use the PAT instead of GITHUB_TOKEN

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance numpy tabulate progress psutil

    - name: Run main.py
      run: python main.py

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    # pull from origin and force push RESULTS.md
    - name: Stash local changes
      run: |
        git stash

    - name: Pull latest changes and accept remote version in case of conflict
      run: |
        git pull --strategy-option=theirs origin main || true

    - name: Restore stashed changes (if any)
      run: |
        git stash pop || echo "No stashed changes to apply"

    - name: Add and Commit Log File
      run: |
        git add RESULTS.md
        git commit -m "New RESULTS.md" || echo "No changes to commit"

    - name: Force push the local version of RESULTS.md
      run: |
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use the PAT for authentication


