name: Run Main File

on:
  schedule:
    - cron: "0 18 * * 1-5" # At 18:00 on working days "0 18 * * 1-5" or every 30 min cron: "*/30 * * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}  # Use the PAT instead of GITHUB_TOKEN

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance numpy tabulate progress psutil

    - name: Run main.py
      run: python main.py

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    # Stash local changes
    - name: Stash local changes
      run: |
        git stash

    # Pull latest changes and accept remote version in case of conflict
    - name: Pull latest changes and accept remote version in case of conflict
      run: |
        git pull --strategy-option=theirs origin main || true

    # Restore stashed changes (if any)
    - name: Restore stashed changes (if any)
      run: |
        git stash pop || echo "No stashed changes to apply"

    # Add and commit all markdown files in the "Result" folder
    - name: Add and Commit Result Files
      run: |
        git add Result/*.md
        git commit -m "Update result files" || echo "No changes to commit"

    # Force push the local version of result files
    - name: Force push the local version of Result files
      run: |
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use the PAT for authentication
